[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "serdebug-derive"
version = "0.1.0"

[dependencies]
quote = "0.6.4"
syn = "0.14.5"

[dev-dependencies]
serde = "1.0.70"
serde_derive = "1.0.70"

[dev-dependencies.serdebug]
path = "../serdebug"

[lib]
proc-macro = true
